name: publish to npm

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  node-publish:
    uses: fluidware-team/.github/.github/workflows/node-publish.yml@584615a8080c045592bf735a92aad8f3e945a91c # v3
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}
