name: publish to npm

on:
  workflow_call:
    secrets:
      npm_token:
        required: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run compile
      - run: npm config set -- '//registry.npmjs.org/:_authToken' "${{ secrets.npm_token }}"
      - run: npm publish --access public
